version: '3.5'

services:

  web:
    build:
      dockerfile: './docker/nginx/Dockerfile'
    volumes:
      - './:/var/www'
      - './docker/nginx/conf.d/prod/:/etc/nginx/conf.d/'
      - '/etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem'
      - '/etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    container_name: cn_nginx
    networks:
        - appnet

  php:
    build:
      dockerfile: './docker/php/Dockerfile'
    volumes:
      - './:/var/www'
      - './logs:/usr/local/php-logs'
    environment:
        - 'PHP_IDE_CONFIG=serverName=santechdebug'
    depends_on:
      - db
    container_name: cn_php
    networks:
        - appnet

  db:
    image: 'mysql:8.0'
    restart: always
    volumes:
      - './db_data:/var/lib/mysql'
    ports:
        - "8101:3306"
    environment:
      MYSQL_DATABASE: 'santech'
      MYSQL_ROOT_PASSWORD: 'root'
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
    container_name: cn_db
    networks:
        - appnet

  phpmyadmin:
    image: 'phpmyadmin'
    restart: always
    ports:
        - "8181:80"
    environment:
        - 'PMA_ARBITRARY=1'
    depends_on:
        - db
    container_name: cn_admin
    networks:
        - appnet

volumes:
    opencart_db_data:
networks:
    appnet:
        name: appnet
        driver: bridge